//defines.h
#define WRITEBYTE(WORD,STARTBITPOS,VAL)\
WORD=((WORD&~(0XFF<<STARTBITPOS))|(VAL<<STARTBITPOS))
#define READBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)
#define READNIBBLE(WORD,STARTBITPOS)\
((WORD>>STARTBITPOS)&15)
#define WRITENIBBLE(WORD,STARTBITPOS,VAL)\
WORD=((WORD&~(15<<STARTBITPOS))|(VAL<<STARTBITPOS))

